ALTER TABLE `ore`
	ADD COLUMN `start` DATETIME NULL DEFAULT NULL AFTER `pagato`,
	ADD COLUMN `stop` DATETIME NULL DEFAULT NULL AFTER `start`,
	ADD COLUMN `location_start` VARCHAR(50) NULL DEFAULT NULL AFTER `stop`,
	ADD COLUMN `location_stop` VARCHAR(50) NULL DEFAULT NULL AFTER `location_start`;